// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.2
// source: proto/coffeed.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetBusyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TimeSpec:
	//
	//	*SetBusyRequest_StartTime
	//	*SetBusyRequest_FromNow
	TimeSpec      isSetBusyRequest_TimeSpec `protobuf_oneof:"time_spec"`
	DurationSpec  *DurationSpec             `protobuf:"bytes,3,opt,name=duration_spec,json=durationSpec,proto3,oneof" json:"duration_spec,omitempty"`
	Reason        *string                   `protobuf:"bytes,5,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBusyRequest) Reset() {
	*x = SetBusyRequest{}
	mi := &file_proto_coffeed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBusyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBusyRequest) ProtoMessage() {}

func (x *SetBusyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBusyRequest.ProtoReflect.Descriptor instead.
func (*SetBusyRequest) Descriptor() ([]byte, []int) {
	return file_proto_coffeed_proto_rawDescGZIP(), []int{0}
}

func (x *SetBusyRequest) GetTimeSpec() isSetBusyRequest_TimeSpec {
	if x != nil {
		return x.TimeSpec
	}
	return nil
}

func (x *SetBusyRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.TimeSpec.(*SetBusyRequest_StartTime); ok {
			return x.StartTime
		}
	}
	return nil
}

func (x *SetBusyRequest) GetFromNow() bool {
	if x != nil {
		if x, ok := x.TimeSpec.(*SetBusyRequest_FromNow); ok {
			return x.FromNow
		}
	}
	return false
}

func (x *SetBusyRequest) GetDurationSpec() *DurationSpec {
	if x != nil {
		return x.DurationSpec
	}
	return nil
}

func (x *SetBusyRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type isSetBusyRequest_TimeSpec interface {
	isSetBusyRequest_TimeSpec()
}

type SetBusyRequest_StartTime struct {
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3,oneof"`
}

type SetBusyRequest_FromNow struct {
	FromNow bool `protobuf:"varint,2,opt,name=from_now,json=fromNow,proto3,oneof"`
}

func (*SetBusyRequest_StartTime) isSetBusyRequest_TimeSpec() {}

func (*SetBusyRequest_FromNow) isSetBusyRequest_TimeSpec() {}

type DurationSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Spec:
	//
	//	*DurationSpec_EndTime
	//	*DurationSpec_Duration
	Spec          isDurationSpec_Spec `protobuf_oneof:"spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationSpec) Reset() {
	*x = DurationSpec{}
	mi := &file_proto_coffeed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationSpec) ProtoMessage() {}

func (x *DurationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationSpec.ProtoReflect.Descriptor instead.
func (*DurationSpec) Descriptor() ([]byte, []int) {
	return file_proto_coffeed_proto_rawDescGZIP(), []int{1}
}

func (x *DurationSpec) GetSpec() isDurationSpec_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DurationSpec) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Spec.(*DurationSpec_EndTime); ok {
			return x.EndTime
		}
	}
	return nil
}

func (x *DurationSpec) GetDuration() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Spec.(*DurationSpec_Duration); ok {
			return x.Duration
		}
	}
	return nil
}

type isDurationSpec_Spec interface {
	isDurationSpec_Spec()
}

type DurationSpec_EndTime struct {
	EndTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=end_time,json=endTime,proto3,oneof"`
}

type DurationSpec_Duration struct {
	Duration *durationpb.Duration `protobuf:"bytes,2,opt,name=duration,proto3,oneof"`
}

func (*DurationSpec_EndTime) isDurationSpec_Spec() {}

func (*DurationSpec_Duration) isDurationSpec_Spec() {}

type SetBusyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBusyResponse) Reset() {
	*x = SetBusyResponse{}
	mi := &file_proto_coffeed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBusyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBusyResponse) ProtoMessage() {}

func (x *SetBusyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBusyResponse.ProtoReflect.Descriptor instead.
func (*SetBusyResponse) Descriptor() ([]byte, []int) {
	return file_proto_coffeed_proto_rawDescGZIP(), []int{2}
}

func (x *SetBusyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetBusyResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_proto_coffeed_proto protoreflect.FileDescriptor

var file_proto_coffeed_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x64, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf2, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x42, 0x75, 0x73, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x77, 0x12, 0x3f, 0x0a, 0x0d,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x48, 0x01, 0x52, 0x0c, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x70, 0x65, 0x63, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x37,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22,
	0x46, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x42, 0x75, 0x73, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x4e, 0x0a, 0x0e, 0x43, 0x6f, 0x66, 0x66, 0x65,
	0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x53, 0x65, 0x74,
	0x42, 0x75, 0x73, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x53,
	0x65, 0x74, 0x42, 0x75, 0x73, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x75, 0x73, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_coffeed_proto_rawDescOnce sync.Once
	file_proto_coffeed_proto_rawDescData []byte
)

func file_proto_coffeed_proto_rawDescGZIP() []byte {
	file_proto_coffeed_proto_rawDescOnce.Do(func() {
		file_proto_coffeed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coffeed_proto_rawDesc), len(file_proto_coffeed_proto_rawDesc)))
	})
	return file_proto_coffeed_proto_rawDescData
}

var file_proto_coffeed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_coffeed_proto_goTypes = []any{
	(*SetBusyRequest)(nil),        // 0: coffeed.SetBusyRequest
	(*DurationSpec)(nil),          // 1: coffeed.DurationSpec
	(*SetBusyResponse)(nil),       // 2: coffeed.SetBusyResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 4: google.protobuf.Duration
}
var file_proto_coffeed_proto_depIdxs = []int32{
	3, // 0: coffeed.SetBusyRequest.start_time:type_name -> google.protobuf.Timestamp
	1, // 1: coffeed.SetBusyRequest.duration_spec:type_name -> coffeed.DurationSpec
	3, // 2: coffeed.DurationSpec.end_time:type_name -> google.protobuf.Timestamp
	4, // 3: coffeed.DurationSpec.duration:type_name -> google.protobuf.Duration
	0, // 4: coffeed.CoffeedService.SetBusy:input_type -> coffeed.SetBusyRequest
	2, // 5: coffeed.CoffeedService.SetBusy:output_type -> coffeed.SetBusyResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_coffeed_proto_init() }
func file_proto_coffeed_proto_init() {
	if File_proto_coffeed_proto != nil {
		return
	}
	file_proto_coffeed_proto_msgTypes[0].OneofWrappers = []any{
		(*SetBusyRequest_StartTime)(nil),
		(*SetBusyRequest_FromNow)(nil),
	}
	file_proto_coffeed_proto_msgTypes[1].OneofWrappers = []any{
		(*DurationSpec_EndTime)(nil),
		(*DurationSpec_Duration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coffeed_proto_rawDesc), len(file_proto_coffeed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coffeed_proto_goTypes,
		DependencyIndexes: file_proto_coffeed_proto_depIdxs,
		MessageInfos:      file_proto_coffeed_proto_msgTypes,
	}.Build()
	File_proto_coffeed_proto = out.File
	file_proto_coffeed_proto_goTypes = nil
	file_proto_coffeed_proto_depIdxs = nil
}
