// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/coffeed.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeedService_SetBusy_FullMethodName = "/coffeed.CoffeedService/SetBusy"
)

// CoffeedServiceClient is the client API for CoffeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoffeedServiceClient interface {
	SetBusy(ctx context.Context, in *SetBusyRequest, opts ...grpc.CallOption) (*SetBusyResponse, error)
}

type coffeedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeedServiceClient(cc grpc.ClientConnInterface) CoffeedServiceClient {
	return &coffeedServiceClient{cc}
}

func (c *coffeedServiceClient) SetBusy(ctx context.Context, in *SetBusyRequest, opts ...grpc.CallOption) (*SetBusyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBusyResponse)
	err := c.cc.Invoke(ctx, CoffeedService_SetBusy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoffeedServiceServer is the server API for CoffeedService service.
// All implementations must embed UnimplementedCoffeedServiceServer
// for forward compatibility.
type CoffeedServiceServer interface {
	SetBusy(context.Context, *SetBusyRequest) (*SetBusyResponse, error)
	mustEmbedUnimplementedCoffeedServiceServer()
}

// UnimplementedCoffeedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeedServiceServer struct{}

func (UnimplementedCoffeedServiceServer) SetBusy(context.Context, *SetBusyRequest) (*SetBusyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBusy not implemented")
}
func (UnimplementedCoffeedServiceServer) mustEmbedUnimplementedCoffeedServiceServer() {}
func (UnimplementedCoffeedServiceServer) testEmbeddedByValue()                        {}

// UnsafeCoffeedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeedServiceServer will
// result in compilation errors.
type UnsafeCoffeedServiceServer interface {
	mustEmbedUnimplementedCoffeedServiceServer()
}

func RegisterCoffeedServiceServer(s grpc.ServiceRegistrar, srv CoffeedServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoffeedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeedService_ServiceDesc, srv)
}

func _CoffeedService_SetBusy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBusyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeedServiceServer).SetBusy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeedService_SetBusy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeedServiceServer).SetBusy(ctx, req.(*SetBusyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoffeedService_ServiceDesc is the grpc.ServiceDesc for CoffeedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coffeed.CoffeedService",
	HandlerType: (*CoffeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBusy",
			Handler:    _CoffeedService_SetBusy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coffeed.proto",
}
